version: "3"

services:
  # mysql:
  #   image: yobasystems/alpine-mariadb
  #   restart: always
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   environment:
  #       - MYSQL_ROOT_PASSWORD=traccar
  #       - MYSQL_DATABASE=traccar
  #       - MYSQL_USER=traccar
  #       - MYSQL_PASSWORD=traccar
  #       - MYSQL_CHARSET=utf8mb4
  #       - MYSQL_COLLATION=utf8mb4_unicode_ci

  builder:
    image: ghcr.io/drolx/track-builder:latest
    build:
      context: docker
      dockerfile: Dockerfile.builder

  alpine:
    image: ghcr.io/drolx/track:alpine
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.alpine
      args:
        TRACCAR_VERSION: 5.10
  
  debian:
    image: ghcr.io/drolx/track:debian
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.debian
      args:
        TRACCAR_VERSION: 5.10
  
  ubuntu:
    image: ghcr.io/drolx/track:ubuntu
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.ubuntu
      args:
        TRACCAR_VERSION: 5.10

