name: deploy builder container image

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  REPO: ghcr.io/${{ github.repository }}-builder

jobs:
  deploy-builder:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          ref: master
          fetch-depth: 0
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set environment DOCKERHUB_IMAGE_PLATFORMS
        run: |
          _DOCKERHUB_IMAGE_PLATFORMS="linux/amd64"
          if [ "${{ matrix.os }}" == "debian" ]; then
            _DOCKERHUB_IMAGE_PLATFORMS+=",linux/arm64"
          elif [ "${{ matrix.os }}" == "ubuntu" ]; then
            _DOCKERHUB_IMAGE_PLATFORMS+=",linux/arm/v7,linux/arm64"
          fi
          echo "DOCKERHUB_IMAGE_PLATFORMS=$_DOCKERHUB_IMAGE_PLATFORMS" >> $GITHUB_ENV

      - name: Build and push Docker image Trace
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.builder
          push: true
          platforms: ${{ env.DOCKERHUB_IMAGE_PLATFORMS }}
          tags: ${{ env.REPO }}:latest,${{ env.REPO }}:1.0
