name: deploy builder container image

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  REPO: ghcr.io/${{ github.repository }}-builder

jobs:
  deploy-builder:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          ref: main
          fetch-depth: 0
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image Trace
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.builder
          push: true
          tags: ${{ env.REPO }}:latest,${{ env.REPO }}:1.0
